a = input('Primul nume este: ')
b = input('Al doilea nume este: ')
print('Lungimea primului nume :', len(a))
print('Numele date sunt la fel: ', a == b)
print('Primul nume mai lung decat al doilea: ', len(a) > len(b))
print('Initiala primului nume: ', a[0])
print('Numele de referinta inversat este: ', a[::-1])
n = int(input('Introduceti un numar: '))
print(a * n)
